services:
  oracle-db:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle-db
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_PWD=adminadmin
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - ./docker/oracle-db/scripts:/opt/oracle/scripts/startup