CREATE OR REPLACE SEQUENCE C##TEST.PEOPLE_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE OR REPLACE SEQUENCE C##TEST.EMAILS_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE OR REPLACE SEQUENCE C##TEST.ADRESSES_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE C##TEST.PHONES_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;